data:
  datasets_raw:
    path: "data/small/datasets_raw_small.csv"
    url: "https://data.gov.cz/soubor/datov%C3%A9-sady.csv"
  datasets:
    path: "data/small/datasets_small.json"
  sparql_endpoint: "https://data.gov.cz/sparql"
  distributions_raw:
    path: "data/distributions_raw.csv"
    url: "https://data.gov.cz/soubor/distribuce.csv"
  distributions:
    path: "data/distributions.json"
state_dir: "state"
app_url: "http://127.0.0.1:5000/"
db:
  host: "postgres"
  port: 5432
  document_table: documents_test
  vector_table: embeddings_test
  embed_dim: 2560
embedding:
  model_name: "qwen3-embedding:4b"
  base_url: http://ollama_proxy:11434
  chunk_size: 16192
  chunk_overlap: 50
  embed_batch_size: 100
  url_to_node_id_mapping_file: "url_to_node_id_mapping_test.json"
search_platform:
  llm:
    model_name: "mistral-small3.2:latest"
    base_url: http://ollama_proxy:11434
    context_length: 4096
    memory_limit: 4096
    timeout: 60
  preprocessing:
    detect_intent: true
    extend_query: true
    timeout: 60
  retriever:
    top_k: 40
    vector_top_k: 25
    bm25_top_k: 25
    mode: relative_score
    retriever_weights:
      - 0.6  # vector_retriever
      - 0.4  # bm25_retriever
    bm25_retriever_persist_dir: "bm25_retriever_small"
  postprocessing:
    reranker: simple  # simple / cross_encoder
    cross_encoder_model: "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1"  # only used for cross_encoder reranker
    top_k: 30
    score_cutoff: 0.2
data_processing:
  llm:
    model_name: "mistral-small3.2:latest"
    base_url: http://ollama_proxy:11434
    context_length: 4096
    timeout: 120
  knowledge_graph:
    name: "test_graph"
    top_k: 5
    similarity_threshold: 0.7
  column_mapping:
    název: title
    popis: description
    datová_sada: url
    klíčová_slova: keywords
    téma: themes
    poskytovatel: provider
    prostorové_pokrytí: spatial_coverage
    časové_pokrytí: temporal_coverage
  distribution_column_mapping:
    název: title
    datová_sada: dataset_url
    přístupovéUrl: url
    formátSouboru: file_format
  irrelevant_columns:
    - kategorie_hvd_IRI  # mostly None and should only be use for legislation related data
    - kategorie_hvd_název  # mostly None and should only be use for legislation related data
    - je_součástí_IRI  # always empty
    - periodicita_aktualizace_IRI  # not relevant
    - periodicita_aktualizace  # not relevant
    - téma_IRI  # keeping "téma" column is enough
    - poskytovatel_IRI  # keeping "poskytovatel" column is enough
    - prostorové_pokrytí  # we will extract spatial_coverage using SPARQL
    - právní_předpis  # not relevant
  categories:
    - Zemědělství, rybolov, lesnictví a výživa
    - Vzdělávání, kultura a sport
    - Životní prostředí
    - Energie
    - Doprava
    - Věda a technika
    - Hospodářství a finance
    - Populace a společnost
    - Zdraví
    - Vláda a veřejný sektor
    - Regiony a města
    - Spravedlnost, právní systém a veřejná bezpečnost
    - Mezinárodní otázky
  other_category: Jiné
    # Based on categories from the EU data portal -
    #        https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme"""