data:
  datasets_raw:
#    path: "data/golden/datove_sady_small.csv"
    path: "data//datove_sady.csv"
    url: "https://data.gov.cz/soubor/datov%C3%A9-sady.csv"
  datasets:
#    path: "data/golden/datasets_with_metadata_small.json"
    path: "data//datasets_with_metadata_large.json"
  sparql_endpoint: "https://data.gov.cz/sparql"
state_dir: "state"
url: "http://127.0.0.1:5000/"
db:
  host: "localhost"
  port: 5432
  document_table: "documents_large_better_preprocessing"
  vector_table: "embeddings_large_better_preprocessing"
  embed_dim: 4096  # 2560
embedding:
  model_name: "qwen3-embedding:latest"  # "qwen3-embedding:4b"
  base_url: "http://localhost:11434"
  chunk_size: 16192
  chunk_overlap: 50
  embed_batch_size: 100
  url_to_node_id_mapping_file: "url_to_node_id_mapping.json"
llm:
  model_name: "mistral-small3.2:latest"
  base_url: "http://localhost:11434"
  context_length: 30000
  memory_limit: 8192
chatbot:
  llm:
    model_name: "mistral-small3.2"
    base_url: "http://localhost:11434"
    context_length: 4096
    memory_limit: 4096
pipeline_config:
  preprocessing:
    detect_intent: true
    extend_query: true
  search:
    top_k: 30
    vector_top_k: 20
    bm25_top_k: 20
    mode: relative_score
    retriever_weights:
      - 0.7  # vector_retriever
      - 0.3  # bm25_retriever
  postprocessing:
    reranker: simple  # simple / llm / sentence_transformer
    sentence_transformer_model: "cross-encoder/ms-marco-MiniLM-L-2-v2"  # only used for sentence_transformer reranker
    top_k: 20  # only used for llm and sentence_transformer rerankers
    score_cutoff: 0.2
data_processing:
  knowledge_graph:
    top_k: 5
    similarity_threshold: 0.7
  column_mapping:
    název: title
    popis: description
    datová_sada: url
    klíčová_slova: keywords
    téma: themes
    poskytovatel: provider
    prostorové_pokrytí: spatial_coverage
    časové_pokrytí: temporal_coverage
  unwanted_columns:
    - kategorie_hvd_IRI  # mostly None and should only be use for legislation related data
    - kategorie_hvd_název  # mostly None and should only be use for legislation related data
    - je_součástí_IRI  # always empty
    - periodicita_aktualizace_IRI  # not relevant
    - periodicita_aktualizace  # not relevant
    - téma_IRI  # keeping "téma" column is enough
    - poskytovatel_IRI  # keeping "poskytovatel" column is enough
    - prostorové_pokrytí  # we will extract spatial_coverage using SPARQL
    - právní_předpis  # not relevant
  categories:
    - Zemědělství, rybolov, lesnictví a výživa
    - Vzdělávání, kultura a sport
    - Životní prostředí
    - Energie
    - Doprava
    - Věda a technika
    - Hospodářství a finance
    - Populace a společnost
    - Zdraví
    - Vláda a veřejný sektor
    - Regiony a města
    - Spravedlnost, právní systém a veřejná bezpečnost
    - Mezinárodní otázky
  other_category: Jiné
    # Based on categories from the EU data portal -
    #        https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme"""