server {
    listen 11434;
    listen [::]:11434;
    client_max_body_size 64M;

    location / {
        proxy_pass http://ollama_tunnel:11434;
        proxy_set_header Host localhost;
        proxy_read_timeout 600s;
        proxy_connect_timeout 60s;
        proxy_send_timeout 600s;
    }
}