[project]
name = 'EnhancedDatasetSearch'
requires-python = ">=3.12"
version = "1.0.0"
authors = [
    {name = "Lucie Vomelová", email = "lucka.vomelova@seznam.cz"},
]

dependencies = [
    "bm25s==0.2.14",
    "certifi==2026.1.4",
    "click==8.3.0",
    "Flask==3.1.2",
    "Jinja2==3.1.6",
    "llama-cloud==0.1.35",
    "llama-cloud-services==0.6.54",
    "llama-index==0.14.8",
    "llama-index-core==0.14.8",
    "llama-index-embeddings-ollama==0.8.6",
    "llama-index-llms-ollama==0.9.0",
    "llama-index-retrievers-bm25==0.6.5",
    "llama-index-storage-docstore-postgres==0.4.1",
    "llama-index-storage-kvstore-postgres==0.4.3",
    "llama-index-vector-stores-postgres==0.7.1",
    "neo4j==6.0.3",
    "nest-asyncio==1.6.0",
    "numpy==2.3.4",
    "ollama==0.6.0",
    "pandas==2.2.3",
    "pgvector==0.4.1",
    "psycopg2==2.9.11",
    "psycopg2-binary==2.9.11",
    "PyYAML==6.0.3",
    "tqdm==4.67.1",
    "scikit-learn==1.8.0",
    "torch==2.10.0",
    "sentence-transformers==5.3.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
