data:
  datasets:
    path: "data/small/datove_sady_small.csv"
    url: "https://data.gov.cz/soubor/datov%C3%A9-sady.csv"
  extended_df:
    path: "data/small/datasets_with_metadata_small.csv"
  distribution:
    path: "data/distribuce.csv"
    url: "https://data.gov.cz/soubor/distribuce.csv"
rag:
  db:
    host: "localhost"
    port: 5432
    document_table: "documents_eval"
    vector_table: "embeddings_eval"
    embed_dim: 4096
  embedding:
    model_name: "qwen3-embedding"
    base_url: "http://localhost:11434"
    chunk_size: 8192
    chunk_overlap: 50
    embed_batch_size: 200
  llm:
    model_name: "mistral-small3.2"
    model_name2: "mistral-small3.2"
    base_url: "http://localhost:11434"
    context_length: 30000
    memory_limit: 8192
  data_processing:
    column_mapping:
      název: title
      popis: description
      datová_sada: url
      klíčová_slova: keywords
      téma: themes
      poskytovatel: provider
      právní_předpis: legal_regulations
      prostorové_pokrytí: spatial_coverage
    unwanted_columns:
      - kategorie_hvd_IRI  # mostly None and should only be use for legislation related data
      - kategorie_hvd_název  # mostly None and should only be use for legislation related data
      - je_součástí_IRI  # always empty
      - periodicita_aktualizace_IRI  # not relevant
      - periodicita_aktualizace  # not relevant
      - téma_IRI  # keeping "téma" column is enough
      - poskytovatel_IRI  # keeping "poskytovatel" column is enough
    categories:
      - Zemědělství, rybolov, lesnictví a výživa
      - Vzdělávání, kultura a sport
      - Životní prostředí
      - Energie
      - Doprava
      - Věda a technika
      - Hospodářství a finance
      - Populace a společnost
      - Zdraví
      - Vláda a veřejný sektor
      - Regiony a města
      - Spravedlnost, právní systém a veřejná bezpečnost
      - Mezinárodní otázky
    other_category: Jiné
      # Based on categories from the EU data portal -
      #        https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/data-theme"""