data:
  datasets:
    path: "data/datove_sady_small.csv"
    url: "https://data.gov.cz/soubor/datov%C3%A9-sady.csv"
  extended_df:
    path: "data/datasets_with_metadata.csv"
  distribution:
    path: "data/distribuce.csv"
    url: "https://data.gov.cz/soubor/distribuce.csv"
rag:
  db:
    host: "localhost"
    port: 5432
    document_table: "documents_extra_metadata"
    vector_table: "embeddings_extra_metadata"
    embed_dim: 4096
  embedding:
    model_name: "qwen3-embedding"
    base_url: "http://localhost:11434"
    chunk_size: 8192
    chunk_overlap: 50
    embed_batch_size: 200
  llm:
    model_name: "mistral-small3.2"
    base_url: "http://localhost:11434"
    context_length: 8192
    memory_limit: 8192

